"""Print the next strategy TradingView capture task and commands."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from strategy_capture_status import DEFAULT_GOLDEN_DIR, build_report


DEFAULT_EXPORT_DIR = Path(".tmp") / "tradingview-priority"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Show the next pending TradingView strategy capture task.",
    )
    parser.add_argument(
        "--golden-dir",
        type=Path,
        default=DEFAULT_GOLDEN_DIR,
        help="Directory containing golden fixture JSON files.",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="Optional manifest.json generated by strategy_capture_prepare.py.",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Consider non-priority cases after priority cases.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print machine-readable JSON instead of a command checklist.",
    )
    args = parser.parse_args(argv)

    report = build_report(args.golden_dir)
    manifest = load_manifest(args.manifest)
    task = find_next_task(report["cases"], manifest, include_all=args.all)
    if task is None:
        payload = {"status": "complete", "message": "no pending capture task"}
        if args.json:
            print(json.dumps(payload, ensure_ascii=False, indent=2))
        else:
            print(payload["message"])
        return 0

    if args.json:
        print(json.dumps(task, ensure_ascii=False, indent=2))
    else:
        print_task(task)
    return 0


def load_manifest(path: Path | None) -> dict[str, Any] | None:
    if path is None:
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def find_next_task(
    status_cases: list[dict[str, Any]],
    manifest: dict[str, Any] | None,
    *,
    include_all: bool,
) -> dict[str, Any] | None:
    pending = [
        case
        for case in status_cases
        if case["status"] != "captured" and (include_all or case["priority"])
    ]
    if not pending:
        return None

    case = pending[0]
    entry = find_manifest_entry(manifest, case["fixture"], case["case"])
    return build_task(case, entry)


def find_manifest_entry(
    manifest: dict[str, Any] | None,
    fixture: str,
    case_name: str,
) -> dict[str, Any] | None:
    if manifest is None:
        return None
    for entry in manifest.get("entries", []):
        if entry.get("fixture") == fixture and entry.get("case") == case_name:
            return entry
    return None


def build_task(
    status_case: dict[str, Any],
    manifest_entry: dict[str, Any] | None,
) -> dict[str, Any]:
    fixture = status_case["fixture"]
    case_name = status_case["case"]
    export_dir = DEFAULT_EXPORT_DIR.as_posix()
    task = {
        "status": "pending",
        "fixture": fixture,
        "case": case_name,
        "priority": status_case["priority"],
        "capture_status": status_case["status"],
        "prepare_command": (
            "python scripts/strategy_capture_prepare.py "
            f"--out-dir {export_dir} --clean"
        ),
        "preflight_command": (
            "python scripts/strategy_capture_preflight.py "
            f"{export_dir}/manifest.json --case {case_name}"
        ),
        "import_command": (
            "python scripts/strategy_capture_import.py "
            f"tests/golden/{fixture} --case {case_name} "
            f"--values {export_dir}/<export.csv> "
            '--tolerance 1e-9 --note "TradingView export YYYY-MM-DD"'
        ),
        "diff_command": (
            f"python scripts/strategy_capture_diff.py tests/golden/{fixture} "
            f"--case {case_name}"
        ),
    }
    if manifest_entry is not None:
        task.update(
            {
                "pine_file": manifest_entry["pine_file"],
                "bars_file": manifest_entry["bars_file"],
                "expected_export_file": manifest_entry["expected_export_file"],
                "plot_titles": manifest_entry["plot_titles"],
                "bar_count": manifest_entry["bar_count"],
                "import_command": manifest_entry["import_command"].replace(
                    "<export-dir>",
                    export_dir,
                ),
                "diff_command": manifest_entry["diff_command"],
            }
        )
    return task


def print_task(task: dict[str, Any]) -> None:
    print("Next strategy TradingView capture task")
    print(f"fixture: {task['fixture']}")
    print(f"case: {task['case']}")
    print(f"priority: {'yes' if task['priority'] else 'no'}")
    print(f"status: {task['capture_status']}")
    if "pine_file" in task:
        print(f"pine file: {task['pine_file']}")
        print(f"bars file: {task['bars_file']}")
        print(f"expected export: {task['expected_export_file']}")
        print(f"bar count: {task['bar_count']}")
        print("plots: " + ", ".join(task["plot_titles"]))
    print()
    print("Commands:")
    print(task["prepare_command"])
    print(task["preflight_command"])
    print(task["import_command"])
    print(task["diff_command"])
    print("python -m pytest tests/test_golden_strategy.py -q")


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
