"""Preflight TradingView CSV exports before importing strategy captures."""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any

from strategy_capture_import import IGNORED_CSV_COLUMNS


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Validate TradingView CSV exports against a capture manifest.",
    )
    parser.add_argument(
        "manifest",
        type=Path,
        help="Path to a manifest.json generated by strategy_capture_prepare.py.",
    )
    parser.add_argument(
        "--export-dir",
        type=Path,
        default=None,
        help="Directory containing TradingView export CSV files. Defaults to manifest parent.",
    )
    parser.add_argument(
        "--case",
        action="append",
        default=[],
        help="Only inspect a named case. May be repeated.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print machine-readable JSON instead of a table.",
    )
    args = parser.parse_args(argv)

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    export_dir = args.export_dir if args.export_dir is not None else args.manifest.parent
    report = build_report(
        manifest=manifest,
        manifest_dir=args.manifest.parent,
        export_dir=export_dir,
        case_filter=set(args.case),
    )
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        print_table(report)
    return 1 if report["counts"]["issues"] else 0


def build_report(
    *,
    manifest: dict[str, Any],
    manifest_dir: Path,
    export_dir: Path,
    case_filter: set[str],
) -> dict[str, Any]:
    cases: list[dict[str, Any]] = []
    issues: list[dict[str, Any]] = []
    for entry in manifest.get("entries", []):
        if case_filter and entry["case"] not in case_filter:
            continue
        case_report = check_entry(entry, manifest_dir, export_dir)
        cases.append(case_report)
        issues.extend(case_report["issues"])

    return {
        "counts": {
            "cases": len(cases),
            "ok": sum(not case["issues"] for case in cases),
            "issues": len(issues),
        },
        "cases": cases,
        "issues": issues,
    }


def check_entry(
    entry: dict[str, Any],
    manifest_dir: Path,
    export_dir: Path,
) -> dict[str, Any]:
    case_report: dict[str, Any] = {
        "fixture": entry["fixture"],
        "case": entry["case"],
        "export_file": entry["expected_export_file"],
        "bar_count": entry["bar_count"],
        "plot_titles": entry["plot_titles"],
        "issues": [],
    }
    export_path = export_dir / entry["expected_export_file"]
    bars_path = manifest_dir / entry["bars_file"]
    if not export_path.exists():
        add_issue(case_report, "missing_export", f"missing export file: {export_path}")
        return case_report

    export = read_csv(export_path)
    expected_plots = set(entry["plot_titles"])
    plot_columns = [
        column
        for column in export["fieldnames"]
        if column.strip().lower() not in IGNORED_CSV_COLUMNS
    ]
    missing_plots = sorted(expected_plots - set(plot_columns))
    unknown_plots = sorted(set(plot_columns) - expected_plots)
    if missing_plots:
        add_issue(
            case_report,
            "missing_plot",
            "missing plot column(s): " + ", ".join(missing_plots),
        )
    if unknown_plots:
        add_issue(
            case_report,
            "unknown_plot",
            "unknown plot column(s): " + ", ".join(unknown_plots),
        )

    row_count = len(export["rows"])
    if row_count != entry["bar_count"]:
        add_issue(
            case_report,
            "row_count",
            f"row count {row_count} does not match expected bar count {entry['bar_count']}",
        )

    if "time" in export["normalized_fieldnames"] and bars_path.exists():
        bars = read_csv(bars_path)
        expected_time = [row.get("time", "") for row in bars["rows"]]
        exported_time = [row.get(export["time_column"], "") for row in export["rows"]]
        if exported_time != expected_time:
            add_issue(case_report, "time_alignment", "time column does not match bars file")

    return case_report


def read_csv(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            raise SystemExit(f"{path}: CSV export must contain a header row")
        fieldnames = [field for field in reader.fieldnames if field is not None]
        normalized = [field.strip().lower() for field in fieldnames]
        time_column = next(
            (field for field in fieldnames if field.strip().lower() == "time"),
            None,
        )
        return {
            "fieldnames": fieldnames,
            "normalized_fieldnames": normalized,
            "time_column": time_column,
            "rows": list(reader),
        }


def add_issue(case_report: dict[str, Any], kind: str, message: str) -> None:
    case_report["issues"].append(
        {
            "fixture": case_report["fixture"],
            "case": case_report["case"],
            "kind": kind,
            "message": message,
        }
    )


def print_table(report: dict[str, Any]) -> None:
    counts = report["counts"]
    print(
        "Strategy TradingView capture preflight: "
        f"{counts['ok']}/{counts['cases']} ok, {counts['issues']} issue(s)"
    )
    if not report["issues"]:
        return
    print()
    print(f"{'fixture':<55} {'case':<44} {'kind':<16} message")
    print("-" * 140)
    for issue in report["issues"]:
        print(
            f"{issue['fixture']:<55} {issue['case']:<44} "
            f"{issue['kind']:<16} {issue['message']}"
        )


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
