"""Print the next TA TradingView capture task and commands."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from ta_capture_status import DEFAULT_GOLDEN_DIR, build_report


DEFAULT_EXPORT_DIR = Path(".tmp") / "tradingview-ta"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Show the next pending TradingView TA capture task.",
    )
    parser.add_argument(
        "--golden-dir",
        type=Path,
        default=DEFAULT_GOLDEN_DIR,
        help="Directory containing golden fixture JSON files.",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="Optional manifest.json generated by ta_capture_prepare.py.",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Consider non-priority fixtures after priority fixtures.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print machine-readable JSON instead of a command checklist.",
    )
    args = parser.parse_args(argv)

    report = build_report(args.golden_dir)
    manifest = load_manifest(args.manifest)
    task = find_next_task(report["fixtures"], manifest, include_all=args.all)
    if task is None:
        payload = {"status": "complete", "message": "no pending TA capture task"}
        if args.json:
            print(json.dumps(payload, ensure_ascii=False, indent=2))
        else:
            print(payload["message"])
        return 0

    if args.json:
        print(json.dumps(task, ensure_ascii=False, indent=2))
    else:
        print_task(task)
    return 0


def load_manifest(path: Path | None) -> dict[str, Any] | None:
    if path is None:
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def find_next_task(
    status_fixtures: list[dict[str, Any]],
    manifest: dict[str, Any] | None,
    *,
    include_all: bool,
) -> dict[str, Any] | None:
    pending = [
        fixture
        for fixture in status_fixtures
        if fixture["status"] != "captured" and (include_all or fixture["priority"])
    ]
    if not pending:
        return None

    fixture = pending[0]
    entry = find_manifest_entry(manifest, fixture["fixture"])
    return build_task(fixture, entry)


def find_manifest_entry(
    manifest: dict[str, Any] | None,
    fixture_name: str,
) -> dict[str, Any] | None:
    if manifest is None:
        return None
    for entry in manifest.get("entries", []):
        if entry.get("fixture") == fixture_name:
            return entry
    return None


def build_task(
    status_fixture: dict[str, Any],
    manifest_entry: dict[str, Any] | None,
) -> dict[str, Any]:
    fixture = status_fixture["fixture"]
    export_dir = DEFAULT_EXPORT_DIR.as_posix()
    task = {
        "status": "pending",
        "fixture": fixture,
        "name": status_fixture["name"],
        "priority": status_fixture["priority"],
        "capture_status": status_fixture["status"],
        "prepare_command": (
            "python scripts/ta_capture_prepare.py "
            f"--out-dir {export_dir} --clean"
        ),
        "preflight_command": (
            "python scripts/ta_capture_preflight.py "
            f"{export_dir}/manifest.json --fixture {fixture}"
        ),
        "import_command": (
            "python scripts/ta_capture_import.py "
            f"tests/golden/{fixture} --values {export_dir}/<export.csv> "
            '--tolerance 1e-9 --note "TradingView export YYYY-MM-DD"'
        ),
        "diff_command": (
            "python scripts/ta_capture_diff.py "
            f"--assertion {capture_diff_assertion(status_fixture)} tests/golden/{fixture}"
        ),
    }
    if manifest_entry is not None:
        task.update(
            {
                "pine_file": manifest_entry["pine_file"],
                "bars_file": manifest_entry["bars_file"],
                "expected_export_file": manifest_entry["expected_export_file"],
                "plot_titles": manifest_entry["plot_titles"],
                "capture_index_title": manifest_entry["capture_index_title"],
                "bar_count": manifest_entry["bar_count"],
                "import_command": manifest_entry["import_command"].replace(
                    "<export-dir>",
                    export_dir,
                ),
                "diff_command": manifest_entry["diff_command"],
            }
        )
    return task


def capture_diff_assertion(status_fixture: dict[str, Any]) -> str:
    if status_fixture["status"] == "captured":
        return status_fixture.get("assertion", "parity")
    return "reference"


def print_task(task: dict[str, Any]) -> None:
    print("Next TA TradingView capture task")
    print(f"fixture: {task['fixture']}")
    print(f"name: {task['name']}")
    print(f"priority: {'yes' if task['priority'] else 'no'}")
    print(f"status: {task['capture_status']}")
    if "pine_file" in task:
        print(f"pine file: {task['pine_file']}")
        print(f"bars file: {task['bars_file']}")
        print(f"expected export: {task['expected_export_file']}")
        print(f"bar count: {task['bar_count']}")
        print("plots: " + ", ".join(task["plot_titles"]))
        print(f"capture index plot: {task['capture_index_title']}")
    print()
    print("Commands:")
    print(task["prepare_command"])
    print(task["preflight_command"])
    print(task["import_command"])
    print(task["diff_command"])
    print("python -m pytest tests/test_golden_ta.py -q")


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
